### PR TITLE
Update deprecated PHPUnit XML schema (which is used by PHPUnit 9.0)

### PR DESCRIPTION
**Pull request by Jhnbrn90**
## What has been done
- Migrated the PHPUnit XML schema to the new PHPUnit 9.0 configuration, using the `--migrate-configuration` option

### CODE REVIEW

**Comment by Jeroen-G** [comment]
Why the .bak file?

**Comment by Jhnbrn90** [comment]
I'd thought to include it because it was generated automatically as a backup file as part of running the above mentioned command. 

If you don't want to include this backup file, I can update the PR.

**Comment by Jeroen-G** [comment]
Git keeps track of the old version, so no need I guess.

**Comment by Jhnbrn90** [comment]
> Git keeps track of the old version, so no need I guess.

Check ✅  Removed the `.bak` file.

**Pull request merged**
