### PR TITLE
Add ability to set timeout

### PR DESCRIPTION
**Pull request by timhaak**
Hi

Kept having timeout when trying to create new projects. (Assuming as in South Africa).

I've added the ability to set the Symphony process timeout for packager:new

### CODE REVIEW

**Comment by Jeroen-G** [comment]
What errors did you get otherwise?

**Comment by timhaak** [comment]
No other errors :).

On this site using the updates a local package and the new flag I was able to create a new package with out it timing out.

**Comment by Jeroen-G** [comment]
I would like to know what is causing the timeout before I merge this PR. :)

**Comment by timhaak** [comment]
As mentioned based in South Africa so our latency as bets is about 200-300ms.

Think as its doing either a composer install or update that is going over the default 60 seconds for Symfony process. 

I also have to increase my composer **process-timeout** to be able to do normal installs and updates. :(

This defaults to 300s so the default for the process of 60 is definitely to low.

**Comment by sebastienheyd** [comment]
I'm totally agree with this ! I also had problems because of the too short timeout on projects with a lot of packages.

But... I think this must be a configuration option instead of a command option because the timeout is applied on every packager command and not only on `new`

Something like this:

```php
$process = new \Symfony\Component\Process\Process($command, base_path());
$process->setTimeout(config('packager.timeout', 60));
$process->run();
```
What do you think about it?

**Comment by timhaak** [comment]
That's actually better.

As should make it more repeatable (You won't forget to set the flag)

**Comment by Jeroen-G** [comment]
I also like the idea of the configuration option more than another command flag.

**Comment by Kristories** [comment]
I think this PR is very useful. 

I've always had this problem : 

```
 0/6 [>---------------------------]   0% Creating package Xxx\Xxx...
Creating packages directory...
Creating vendor...
Downloading skeleton...
 4/6 [==================>---------]  66% Replacing skeleton placeholders...
Installing package...

   Symfony\Component\Process\Exception\ProcessTimedOutException 

  The process "'composer' 'require' 'Xxx/Xxx:@dev'" exceeded the timeout of 60 seconds.
```

Also, I agree with @sebastienheyd to add timeout configuration : 

```
config('packager.timeout', 60)
```

**Comment by timhaak** [comment]
Hi all

Been busy so only got to this now.

I've created a new pull request Jeroen-G/laravel-packager#130 and moved from using a command-line option to a config option.

**Pull request closed without merging**
