### PR TITLE
Close #167

### LINKED ISSUE #167: Windows composer.json problem
On Windows there is the following problem:
```json 
  "test/test4": {
      "type": "path",
      "url": "C:\\xampp\\htdocs\\FORKED\\package-testing\\packages/test/test4",
      "options": {
          "symlink": true
      }
  },
```

The problem is fixed with the following modification:

```php
// FileHandler.php

public function vendorPath()
{
    return $this->packagesPath().'\\'.$this->vendor();
}

public function packagePath()
{
    return $this->vendorPath().'\\'.$this->package();
}
```

The result is now correct:

```json
"test/test5": {
    "type": "path",
    "url": "C:\\xampp\\htdocs\\FORKED\\package-testing\\packages\\test\\test5",
    "options": {
        "symlink": true
    }
},
```

PS I don't know if this affects MacOS

Is it ok if I open a PR for this?

### PR DESCRIPTION
**Pull request by MimisK13**
Fixes package path in composer.json file.

### CODE REVIEW

**Comment by Jeroen-G** [comment]
I'll have to check this because it might not work on other OSes.
Wasn't there a PHP constant that is system specific? 🤔

**Comment by MimisK13** [comment]
Do you mean `PHP_OS`?

It could be a solution

```php
if (PHP_OS === 'WINNT')
{
    return $this->packagesPath() . '\\' . $this->vendor();
}

return $this->packagesPath() . '/' . $this->vendor();
```

**Comment by MimisK13** [comment]
I think this is the solution we are looking for.

```php
public function vendorPath()
{
    return $this->packagesPath().DIRECTORY_SEPARATOR.$this->vendor();
}

public function packagePath()
{
    return $this->vendorPath().DIRECTORY_SEPARATOR.$this->package();
}
```

**Comment by Freezon** [comment]
Hi, this is how it is done in Laravel, I think the PR can be accepted) 
Proof: 
[laravel/framework/src/Illuminate/Foundation/Application.php](https://github.com/laravel/framework/blob/ea4198a1dcb8dcaf5037f7f1f9cb5d9dc2e1a58e/src/Illuminate/Foundation/Application.php#L587-L590)
```php
    public function joinPaths($basePath, $path = '')
    {
        return $basePath.($path != '' ? DIRECTORY_SEPARATOR.ltrim($path, DIRECTORY_SEPARATOR) : '');
    }
```

**Comment by MimisK13** [comment]
bump.

**Comment by MimisK13** [comment]
Good evening. 

The issue still persists on Windows. 

Please accept this solution. 🙏🙏🙏

**Pull request merged**
