### PR TITLE
Composer dump-autoload after new package.

### PR DESCRIPTION
**Pull request by ntavelis**
Hello again,

Made some cleanup, and moved logic into helper class. Also added `$this->helper->dumpAutoloads();` call to the PackagerNewCommand.php.

Note: I removed readme changes from old pull request.

Thank you,
Thanasis

### CODE REVIEW

**Comment by Jeroen-G** [comment]
If you want, you can also dump the autoloads in the get and git and remove command. Otherwise I will do it.
Is it possible to easily throw out the change in the PackagerListCommand file? Makes the squashed commit cleaner.

**Comment by ntavelis** [comment]
Tried to change it, with no success, the two files are identical.

If you don't mind make the changes in the rest commands.

**Comment by Jeroen-G** [comment]
I will release a new version in a couple of days.

**Comment by ntavelis** [comment]
Great !! looking forward to it :D

**Comment by Jeroen-G** [comment]
To make sure it works, could you require dev-master and try it out?

**Pull request merged**
